// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARZ0rfY-rXSvb-ryB0TbmpnGQYlmR8MBo',
    appId: '1:1030622712297:web:fde99aee8cbeec825fbb78',
    messagingSenderId: '1030622712297',
    projectId: 'fir-authentication-380c6',
    authDomain: 'fir-authentication-380c6.firebaseapp.com',
    storageBucket: 'fir-authentication-380c6.appspot.com',
    measurementId: 'G-EXPZRRBV1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqg4kERhCMJIDge8Vr_a4WXBqNkbj5PKs',
    appId: '1:1030622712297:android:657934c5ba36ce9d5fbb78',
    messagingSenderId: '1030622712297',
    projectId: 'fir-authentication-380c6',
    storageBucket: 'fir-authentication-380c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1T6q3HpAWUms6fOIYTiTpnoSqxOlVprA',
    appId: '1:1030622712297:ios:92be6939493bfa095fbb78',
    messagingSenderId: '1030622712297',
    projectId: 'fir-authentication-380c6',
    storageBucket: 'fir-authentication-380c6.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1T6q3HpAWUms6fOIYTiTpnoSqxOlVprA',
    appId: '1:1030622712297:ios:b3a6274ab4ca1d635fbb78',
    messagingSenderId: '1030622712297',
    projectId: 'fir-authentication-380c6',
    storageBucket: 'fir-authentication-380c6.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication.RunnerTests',
  );
}
